### ISSUE TITLE
Error when requesting for a lot of Array data on a single query.

### ISSUE THREAD

**Issue by jfontanet** [Protryon/klickhouse#2]
When performing a select query on a database with big arrays, the channel created to receive the query results get a capacity overflow. 
This is so because it eventually fails to read correctly the size of the array. It looks like the pointer is not correctly placed when reading arrays. (Fixing the size for a quick test returns the array values with 0's at the beginning, so all the values are shifted).
@Protryon

**Comment by Protryon** [comment]
Could you give more details on how to reproduce? I.e. how many rows, how many arrays, what query?

**Comment by Protryon** [comment]
This has been fixed.
