### ISSUE TITLE
Bool type

### ISSUE THREAD

**Issue by gusinacio** [Protryon/klickhouse#25]
Does this library support Bools? It looks like `Value` doesn't have it.

**Comment by Protryon** [comment]
So `Bool` as a protocol-level type is new. Older versions represented them as Int8/UInt8. Newer versions (I think 23+?) do have a `Bool` type. The decoder will implicitly convert `Bool` types to `UInt8` (as 0/1) for compatibility. `bool` implements FromSql/ToSql in the same manner.

If you need to use `Bool` types within `Value`, you can access it via UInt8. I don't think adding an explicit `Bool` variant is a good idea, as it will lead to inconsistent behavior with different versions of Clickhouse.
