### ISSUE TITLE
3+-dimensional arrays

### ISSUE THREAD

**Issue by cpg314** [Protryon/klickhouse#31]
The `Type::validate` method has a check that rejects multidimensional arrays with more than 2 dimensions, e.g. `Array(Array(Array(T)))`: https://github.com/Protryon/klickhouse/blob/master/klickhouse/src/types/mod.rs#L811

Comparing 
https://github.com/Protryon/klickhouse/blob/master/klickhouse/src/types/deserialize/array.rs#L25
with the python implementation
https://github.com/ClickHouse/clickhouse-connect/blob/main/clickhouse_connect/datatypes/container.py#L37
I was not able to find what breaks down for 3 or more dimensions. The Python implementation is more efficient in that it reads all the data at once rather than recursing, but this is all I see for now. 

The following test passes both with integers and with strings as inner type (after commenting out the check):

```rust
#[derive(Debug, Clone, klickhouse::Row, PartialEq)]
struct Row {
    a: Vec<Vec<Vec<u8>>>,
}
#[tokio::test]
async fn test_3d_array() {
    let client = super::get_client().await;
    let items = vec![
        Row {
            a: vec![
                vec![vec![1, 2], vec![3], vec![4, 5, 6]],
                vec![vec![7], vec![8, 9]],
            ],
        },
        Row {
            a: vec![
                vec![vec![10], vec![11, 12, 13], vec![14]],
                vec![vec![15, 16], vec![17]],
                vec![vec![18]],
            ],
        },
    ];

    client
        .execute("drop table if exists test_serialize")
        .await
        .unwrap();
    client
        .execute(
            r"
    CREATE TABLE test_serialize (
    a Array(Array(Array(UInt8)))
    ) ENGINE = Memory;
    ",
        )
        .await
        .unwrap();
    client
        .insert_native_block("insert into test_serialize format native", items.clone())
        .await
        .unwrap();

    let items2 = client
        .query_collect("SELECT * from test_serialize")
        .await
        .unwrap();
    assert_eq!(items, items2);
}
```

Do you remember what the reason for this restriction was?

**Comment by Protryon** [comment]
My previous implementation for array parsing was quite broken and I fixed it a while ago. Should be fine to remove the restriction.

**Comment by cpg314** [comment]
Done in #38
