### ISSUE TITLE
Any mechanism to reconnect clickhouse server when EOF(channel closed)

### ISSUE THREAD

**Issue by pymongo** [Protryon/klickhouse#45]
my clickhouse server is deploy by docker

I have a axum http server with_state klickhouse client to query data in db return in http api

when server started 10 hour has these error message and my http api can't query db data

```
24-02-29 19:21:18.633 ERROR klickhouse::client:212: clickhouse client failed: Io(Custom { kind: UnexpectedEof, error: "early eof" })
24-02-29 20:00:15.221 ERROR db:129: protocol error: failed to send query: channel closed
```

posible solution: how to detect clickhouse client tcp connection EOF and auto reconnect?

**Comment by pymongo** [comment]
another solution, tokio::spawn a task to send `select 1` every 30s to make tcp connection keep alive?

**Comment by negezor** [comment]
I just ran into this problem. We had unstable internet on the server, which completely disrupted the whole service as there is no auto reconnect. I think it's worth introducing pool connections so you don't have to write an abstraction to reconnect every time.

@Protryon sorry for ping, but how do you deal with this problem?

**Comment by Protryon** [comment]
You can enable the bb8 feature in klickhouse then use the bb8 crate to maintain a connection pool. It will handle reconnections and parallel usage.

**Comment by negezor** [comment]
@Protryon thanks for the reply. I didn't notice since it wasn't mentioned in the README and features. I made a PR that clarifies this point https://github.com/Protryon/klickhouse/pull/48
