### ISSUE TITLE
Hard dependency on yanked refinery version?

### ISSUE THREAD

**Issue by richardstephens** [Protryon/klickhouse#70]
When setting up a new project with migrations through refinery, cargo resits adding the dependency because klickhouse depends on refinery 0.8.13, which has been yanked.

It looks like [the issue that caused it to be yanked](https://github.com/rust-db/refinery/issues/323) probably isn't anything to worry about, so I was able to add the dep with

    `cargo +nightly  -Zunstable-options update --precise 0.8.13 refinery`

but would it be possible to update the dependency to 0.8.14?

**Comment by Protryon** [comment]
Fixed, released 0.13.2
